services:
  postgres:
    image: postgres:17
    container_name: green-energy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: green_energy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:2
    container_name: green-energy-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  backend:
    image: node:24-alpine
    container_name: green-energy-backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node app.js"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mqtt

volumes:
  postgres_data:
